#' Simulates Ascochyta spore dispersal for a single day increment
#'
#' @param i_date a character string or POSIXct formatted string indicating an
#'   iteration date of the model. Preferably in \acronym{ISO8601} format
#'   (YYYY-MM-DD), \emph{e.g.} \dQuote{2020-04-26}.
#'
#' @param daily_vals `list` of model variables which have been calculated for
#'   days prior to the `i_date`
#' @param weather_dat `data.table` of weather observations which includes the
#'   query date `i_date`
#' @param max_gp numeric double a function of `max_gp_lim x (1 - exp(-0.138629 x
#'   seeding_rate))
#' @param spore_interception_parameter parameter indicating the probability of a
#'   spore landing on a susceptible growing point
#' @param spores_per_gp_per_wet_hour Number of spores produced per sporulating
#'   growing point each wet hour. Also known as the 'spore_rate'. Value is
#'   dependent on the susceptibility of the host genotype.
#'
#' @return a `list` detailing daily data for the day `i_date` generated by the
#'   model including: a `paddock` an 'x' 'y' data.table, iteration day (i_day),
#'   cumulative daily weather data, such as: cumulative degree days (cdd),
#'   cumulative wet hours (cwh) and cumulative rainfall in mm (cr); standard
#'   growing points assuming growth is not impeded by infection (`gp_standard`),
#'   new growing points produced in the last 24 hours (`new_gp`), an 'xy'
#'   `data.table` of only infectious growing points, and new_infections 'xy'
#'   data.table indicating exposed growing points in the latent period phase of
#'   infection.
#'
#' @keywords internal
#' @noRd
one_day <- function(i_date,
                    daily_vals,
                    weather_dat,
                    gp_rr,
                    max_gp,
                    spore_interception_parameter,
                    spores_per_gp_per_wet_hour) {
  times <- temp <- wet_hours <- rain <- new_gp <- infectious_gp <-
    cdd_at_infection <- susceptible_gp <- NULL

  # expand time to be hourly
  i_time <- rep(i_date, 24) + lubridate::dhours(0:23)

  # subset weather data by day
  weather_day <-
    weather_dat[times %in% i_time,]

  # obtain summary weather for i_day
  i_mean_air_temp <- mean(weather_day[, temp])
  i_wet_hours <- weather_day[2, wet_hours]
  i_rainfall <- sum(weather_day[, rain], na.rm = TRUE)

  # Start building a list of values for 'i'
  # NOTE: I may add this to after `make_some_infective`
  daily_vals[["cdd"]] <- daily_vals[["cdd"]] + i_mean_air_temp
  daily_vals[["cwh"]] <- daily_vals[["cwh"]] + i_wet_hours
  daily_vals[["cr"]] <- daily_vals[["cr"]] + i_rainfall

  # max new growing points are multiplied by five as growing points remain
  # susceptible for five days.
  max_interception_probability <-
    interception_probability(target_density = 5 *
                               max(daily_vals[["paddock"]][, new_gp]),
                             k = spore_interception_parameter)

  # need to make a copy of the data.table otherwise it will modify all
  # data.tables in the following functions
  daily_vals[["paddock"]] <- copy(daily_vals[["paddock"]])
  if (any(is.na(daily_vals[["paddock"]][, infectious_gp]))) {
    stop("NA values in daily_vals[['paddock']][,infectious_gp] ")
  }

  # Don't spread spores if there are no infected coordinates
  if (nrow(daily_vals[["infected_coords"]]) > 0) {
    # Spread spores and infect plants
    # Update growing points for paddock coordinates
    if (i_wet_hours > 2) {
      exposed_dt <-
        rbindlist(
          lapply(
            seq_len(nrow(weather_day[rain >= 0.1,])),
            FUN = spores_each_wet_hour,
            weather_hourly = weather_day[rain >= 0.2,],
            paddock = daily_vals[["paddock"]],
            max_interception_probability = max_interception_probability,
            spore_interception_parameter = spore_interception_parameter,
            spores_per_gp_per_wet_hour = spores_per_gp_per_wet_hour
          )
        )
      exposed_dt[, cdd_at_infection := daily_vals[["cdd"]]]


      daily_vals[["exposed_gps"]] <-
        rbind(daily_vals[["exposed_gps"]],
              exposed_dt)


    }

    # exposed gps which have undergone latent period are moved to sporulating gps
    daily_vals <- make_some_infective(daily_vals = daily_vals,
                                      latent_period = 200)


    # update infected coordinates
    daily_vals[["infected_coords"]] <-
      daily_vals[["paddock"]][infectious_gp > 0,
                              c("x", "y")]

  }

  # Grow Plants
  # this code represents mathematica function `growth`; `updateRefUninfectiveGrowingPoints`

  # `updateGrowingPointsAllInfectiveElements`
  # Update Growing points for non-infected coords for time i
  daily_vals[["new_gp"]] <-
    calc_new_gp(
      current_growing_points = daily_vals[["gp_standard"]],
      gp_rr = gp_rr,
      max_gp = max_gp,
      mean_air_temp = i_mean_air_temp
    )



  # this might be quicker if there was no fifelse statement
  daily_vals[["paddock"]][, new_gp := fcase(
    susceptible_gp == 0,
    0,
    susceptible_gp == daily_vals[["gp_standard"]],
    daily_vals[["new_gp"]],
    susceptible_gp < daily_vals[["gp_standard"]],
    calc_new_gp(
      current_growing_points = susceptible_gp,
      gp_rr = gp_rr,
      max_gp = max_gp,
      mean_air_temp = i_mean_air_temp
    )
  )]

  daily_vals[["gp_standard"]] <-
    daily_vals[["gp_standard"]] + daily_vals[["new_gp"]]

  daily_vals[["paddock"]][, susceptible_gp := susceptible_gp + new_gp]

  return(daily_vals[])
}
